version: "3.3"

services:
  bot:
    build: .
    image: telegram-forwarding-bot
    container_name: telegram-forwarding-bot
    volumes:
      - ./.env:/app/.env
      - ./config.json:/app/config.json

